config/routes.rb
NewPrizzmCom::Application.routes.draw do
  get "search/public"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  # API
  namespace :api do
    namespace :v1  do
      resources :tokens,:only => [:create, :destroy]
      resources :topics, :controller=>:topics_api do
        get :trending, on: :collection
      end

      resources :comments
      get 'search', :to => "topics_api#search"
      match "/user/info" => "users_api#info"
      match "/topics/create" => "topics#create"
    end
  end

  # Authentication
  devise_for :users,
    :path_names => {
      :sign_in => '/login',
      :sign_out => '/logout',
      :sign_up => '/join',
    },
    :controllers => {
      :sessions     => "sessions",
      :registrations => "registrations",
      :omniauth_callbacks => "omniauth_callbacks"
    }

  devise_scope :user do
    get "login",   :to => "sessions#new"
    post "login",  :to => "sessions#create"
    get "logout",  :to => "sessions#destroy"
    get "join",  :to => "registrations#new"
    post "join", :to => "registrations#create"
    get 'brands/join', :to => 'registrations#new', :brand => true
  end

  # Payments
  match '/topics/:topic_shortcode/payments/process' => 'payments#processP'
  match '/orders/:order_id/:invoice_id/confirmation' => 'payments#confirmation'
  # Passbook
  match '/passbook/passes/generate' => "passbook#generate"
  match '/passbook/passes/:aftoken' => "passbook#pass"
  match "/passbook/passes/v1/devices/:devid/registrations/:bundleid/:serialnumber" => "passbook#register_device", :constraints => { :bundleid => /[^\/]+/ }
  match "/passbook/passes/v1/passes/:typeid/:serialnumber" => "passbook#get_current_pass", :constraints => { :typeid => /[^\/]+/ }

  # match "/tokens/facebook" => "social#authenticateMobile"
  match "/tokens/facebook" => "social#socialAuthenticationAPIFacebook"
  match "/tokens/twitter" => "social#socialAuthenticationAPITwitter"
  match "/topics/findByMIU" => "social#getShortCode"
  match "/social/mobile/askfriends" => "social#askMobileFriends"

  # Scraping
  post 'get/product' => 'get#product'
  post 'get/images_and_price' => 'get#images'

  # Auth Roots
  get 'welcome' => 'profile#welcome', :as => 'welcome'
  get 'me' => 'profile#show', :as => 'user_root'
  #get 'me' => 'topics#index', :as => 'user_root'
  resource :profile, :controller => "profile"
  resources :haves do
    member do
      get 'copy'
      put 'recommend'
    end
  end

  # Topics
  resources :topics do
    resources :votes, only: :create
    resources :comments, only: :create
    resources :email_shares, only: [:new, :create]

    resources :responses
    get 'login' => 'topics#login'
    get 'thanks' => 'promotions#opinion'

    collection do
      get 'recommendation' => 'topics#new', :topic => { :form => :recommendation }
      get 'business/recommendation' => 'topics#new', :topic => { :form => :business_recommendation }
      get 'recommend' => 'topics#new', :topic => { :form => :recommend }
    end

    member do
      get 'copy'
      get 'bought'
    end
  end

  get 'activity' => 'activity#index'

  # Users
  resources :users, :only => [:index, :show]
  resources :brands, :only => [:index, :show]

  # Products
  resources :products do
    get 'feedback' => 'reviews#feedback'
    get 'feedback/thanks' => 'reviews#thanks'
    resources :reviews
  end

  # Social
  post 'social/tweeted' => 'social#tweeted'
  post 'social/recommended' => 'social#recommended'
  # Sharing
  match 'topics/:sc/social/ask/facebook' => 'social#facebook', as: :social_ask_facebook
  match 'topics/:sc/social/ask/twitter' => 'social#twitter',   as: :social_ask_twitter
  match 'topics/:sc/social/ask/all' => 'social#askAll'
  # Authentication
  match 'users/auth/methods/facebook/uid' => 'social#socialAuthenticationAPI'

  # Linking
  match 'profile/unlink/facebook' => 'social#unlinkFacebookAccount'
  match 'profile/unlink/twitter' => 'social#unlinkTwitterAccount'

  # Router
  get 'share/:shortcode' => "router#shared", :as => :shared
  get 'invited/:shortcode' => "router#invited", :as => :invited
  post 'register' => 'router#register', :as => :register
  post 'join_beta' => 'router#join_beta', :as => :join_beta

  # Uploads
  post 'uploads/accept' => 'upload#accept'


  # Sandbox
  get 'sandbox' => "website#sandbox"

  # Fragments
  get 'partial/:action' => 'fragments'

  # Brands / Shoppers
  get '/shoppers' => 'website#index', :shopper => true

  # Search
  get "/search", :to => "search#public"

  resources :welcomes, only: :index
  resources :tags, :only => :index do
    member do
      get :topics
    end
    collection do
      post :update_tags
    end
  end

  resource :invite do
    put :update_password, on: :member
  end

  # in config/routes.rb
  match "/pages/*id" => 'pages#show', :as => :page, :format => false

  # Root
  root :to => "welcomes#index"
end

app/views/shares/_anonymous_topic_header.html.haml
%ul.nav.nav-tabs.topic-tabs
  %li{'tab-name' => "all"}
    %a{:href => topics_path}
      Everybody

app/views/shares/_flash_notice.html.haml
.flash-notice.fixed-top
  - unless flash[:notice].blank? && flash[:error].blank? && flash[:alert].blank?
    .alert.alert-flash.fade.in{ class: flash[:notice].blank? ? "alert-error" : "alert-success" }
      %button{type: "button", class: "close", :"data-dismiss" => "alert"}
        ×
      .container
        .row
          %strong
            = flash[:notice] unless flash[:notice].blank?
            = flash[:error]  unless flash[:error].blank?
            = flash[:alert]  unless flash[:alert].blank?

app/views/shares/_javascript.html.erb
<script type="text/javascript" src="http://use.typekit.net/zum4xss.js"></script>
<script type="text/javascript">try { Typekit.load(); } catch (e) { }</script>

app/views/shares/_landing_header.html.haml
.header
  .row
    .span4
      = link_to("/") do
        = image_tag("mightbuy-logo.png", id: "mightbuy-logo")
      %p.caption
        = mightbuy_tag_line
    .span2.offset6
      = link_to(new_user_session_path) do
        = image_tag("signin-ribbon.png")

app/views/shares/_login_lightbox.html.haml
#login-lightbox
  .container
    .row
      .span12
        %p.caption
          Thanks for voting or commenting!
          %br
          You need to log in to save your vote or comment
    .row
      .span1
        &nbsp;
      .span5
        %p
          Already a member? Sign-in

        = simple_form_for :user, url: new_user_session_path, remote: true, html: { id: "signin_user" } do |f|
          - if params[:controller] == "sessions"
            = f.input :email
          - else
            = f.input :email, input_html: { value: "" }

          = f.input :password
          %a{:href=>"#"} Forgot your password?
          .user-signin-form-submit
            = f.submit "Sign in!", class: "btn btn-red pull-right"
          .clear

        .row
          .span5.font18.mtop-leftcol
            .pull-right.mright40
              = link_to user_omniauth_authorize_path(:facebook) do
                .facebook-icon.pull-left
              = link_to user_omniauth_authorize_path(:twitter) do
                .twitter-icon.pull-left

            Or you could sign in with
            %br
            Facebook & Twitter!
          .clear


      .span5.col-right
        %p
          Join us today!
        = form_for user, html: { data: { remote: true, type: :json } } do |f|
          .control-group
            = f.label :name, class: 'control-label'
            .controls
              = f.text_field :name, required: false
              .help-inline

          .control-group
            = f.label :password, class: 'control-label'
            .controls
              = f.password_field :password
              .help-inline

          .control-group
            = f.label :email, class: 'control-label'
            .controls
              = f.text_field :email
              .help-inline

          .new-user-form-submit
            = f.submit "Get Started!", class: "btn btn-red pull-right"
          .clear

        .row
          .span5.font18.mtop-rightcol
            .pull-right.mright40
              = link_to user_omniauth_authorize_path(:facebook) do
                .facebook-icon.pull-left
              = link_to user_omniauth_authorize_path(:twitter) do
                .twitter-icon.pull-left

            Or you could also join us
            %br
            with Facebook & Twitter!
          .clear

app/views/shares/_search_header.html.haml
.header
  .row
    .span4
      = link_to("/") do
        = image_tag("mightbuy-logo.png", id: "mightbuy-logo")
      %p.caption
        = mightbuy_tag_line
    .span6.offset2
      .pull-right.top-nav-links
        %a{"data-toggle" => "modal", :href => "#myModal", :role => "button"} Video
        |
        = link_to(new_user_session_path) do
          Sign In
        |
        = link_to(new_user_registration_path) do
          Sign Up

#myModal.hide.modal{"aria-hidden" => "false", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header.modal-header-bg
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Video Demo
  .modal-body
    %iframe{:height => "350", :src => "http://www.youtube.com/embed/9riCsmyrW3g", :width => "520"} 

:javascript
  $('#myModal').modal('hide')

app/views/shares/_shared_sidebar.html.haml
- if current_user
  .avatar.mtop40
    = link_to(user_path(current_user)) do
      = image_tag(avatar_image)

  .profile-actions
    .edit-profile
      - if not current_page?(user_path(current_user))
        = link_to "View Profile", user_path(current_user)
      - else
        = link_to "Edit Profile", edit_profile_path

    .logout
      = link_to "Sign out", destroy_user_session_path, :method => :delete

.topic-tag-list
  - if not current_user or current_page?(topics_path)
    %h2 Popular Tags
    - tags = popular_tags
  - else
    %h2 Personal Tags
    - tags = current_user.popular_tags

  %ul
    - tags.each do |tag|
      %li= link_to(tag.name, topics_tag_path(tag))

app/views/shares/_tags.html.haml
- if topic.owner?(current_user)
  = form_for(topic,url: update_tags_tags_path(:topic_id => topic), html: {id: "topic_add_tag_form"}) do
    %ul{:type => "text", :id => "topic_tags_show", :class => "clearfix", :name => "topic[tags][]"}
- else
  = tag_links(topic)

app/views/shares/_topic_confirm_add_modal.html.haml
.modal.hide.fade{id: "topic-confirm-add-modal-#{topic.id}"}
  .modal-header
    %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
      &times
    %h3 Confirm
  .modal-body
    .row
      .span1.p-rel
        = image_tag(topic.icon_image)
        %span.mask-64
      .span4
        %h4= topic.subject.capitalize
        %p=  link_to(topic.short_url, topic.url, :target=>"_blank")
      %h3.price= number_to_currency(topic.price)
  .modal-footer
    = link_to "Add to 'I mightbuy' list", copy_topic_path(topic), class: "btn btn-red"
    %button.btn.btn-red{"data-dismiss" => "modal", "aria-hidden" => "true"}
      Cancel

app/views/shares/_topic_header.html.haml
= javascript_tag "Mightbuy.selectedMainTab = '#{@selected_tab}'"
= javascript_tag "Mightbuy.suggestedTags = #{popular_tag_array}"
.row
  .span10
    %ul.nav.nav-tabs.topic-tabs
      %li{'tab-name' => "mightbuy"}
        %a{:href => profile_path }
          I MightBuy
      %li{'tab-name' => "ihave"}
        %a{:href => haves_path}
          I Have
      %li{'tab-name' => "everybody"}
        %a{:href => topics_path}
          Browse

      - if @selected_tab != "everybody"
        %li.add-an-item-btn
          = link_to ( @selected_tab == 'mightbuy' ? new_topic_path : new_have_path ) do
            %i.icon-plus-sign.icon-white
            Add an item
      - else
        %li.add-an-item-drop
          %ul.nav.nav-pills.pull-right
            %li.dropdown
              %a#drop5.dropdown-toggle.btn.btn-red{"data-toggle" => "dropdown", :href => "#", :role => "button"}
                %i.icon-plus-sign.icon-white
                Add an item
                %b.caret
              %ul.dropdown-menu{"aria-labelledby" => "drop5", :role => "menu"}
                %li
                  = link_to new_topic_path, tabindex: "-1" do
                    %i.icon-plus
                    Add to Might buy
                %li.divider
                %li
                  = link_to new_have_path, tabindex: "-1" do
                    %i.icon-plus
                    Add to have

app/views/shares/_topic_list_partial.html.haml
%li{id: "topic-browse-entry-#{topic.id}"}
  .row
    .span2.item-list-image.p-rel
      = image_tag(topic.thumbnail_image, :alt => topic.subject, :class =>"shadow")
      = link_to("", topic_path(topic))
    .span7.pull-right
      .row
        .span5
          .topic-title
            = link_to(topic.subject.capitalize, context_topic_path(topic))
          .topic-url
            = link_to(topic.short_url, topic.url, :target=>"_blank")
          .topic-listing-tag
            %i.icon-tags
            tags:
            = tag_links(topic)
          .topic-meta-all.mtop10
            = link_to(topic.poster_name(current_user), user_path(topic.user))
            #{topic.human_status} this
            = link_to copy_topic_path(topic), :rel =>"tooltip", :title =>"This item will be copied to 'mightbuy'", "data-toggle" =>"modal", "data-target" => "#topic-confirm-add-modal-#{topic.id}" do
              = image_tag("add_icon.png")
            = render partial: "shares/topic_confirm_add_modal", locals: { topic: topic }
        .span1.pull-right.topic-list-actions
          %div.price
            - if topic.product && topic.product.price 
              = number_to_currency(topic.product.price)
            - else 
              = number_to_currency(topic.price)
          .clear
        .clear
        %br
        .span7.dotted-border.ptop10
          %div{id: "topic-vote-browse-#{topic.id}"}
            - unless topic.ihave?
              = render partial: "shares/topic_votes_on_browse", locals: { topic: topic, vote: topic.vote_by(current_user) }
            - else
              = recommend_text(topic)
          .pull-right
            .pagination-right.raquo
              = link_to("more   ", context_topic_path(topic))
          .clear
    .clear
    
:javascript
   $(document).ready(function(){
    $('a').tooltip();
  });

app/views/shares/_topic_votes_on_browse.html.haml
.pull-left
  .pull-left.mright10.ptop3.color-brown
    = "Vote - should #{topic.poster_name(current_user)} buy it?"
  .vote-icons.pull-left
    = link_to topic_votes_path(topic, vote: "yes"), method: :post, remote: true do
      .vote-yes{class: vote && vote.buyit ? "checked" : ""}
    = link_to topic_votes_path(topic, vote: "no"), method: :post, remote: true do
      .vote-no{class: vote && !vote.buyit ? "checked" : ""}
  .clear

app/views/shares/javascript.html.erb
<script type="text/javascript" src="//use.typekit.net/zum4xss.js"></script>
<script type="text/javascript">try { Typekit.load(); } catch (e) { }</script>

app/views/shares/new.html.slim
= app_page do
  ol.list.topics
    = render parent
    
  = heading "Share via.."
  
  = simple_form_for parent, :url => collection_path, :method => :post do |form|
    = form.simple_fields_for :shares, resources do |fields|
      = render "share_fields", :f => fields
    .links
      = link_to_add_association 'Send to another friend..', form, :shares
      
    .buttons
      = form.button :submit, "Send!"