config/routes.rb
NewPrizzmCom::Application.routes.draw do
  get "search/public"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  # API
  namespace :api do
    namespace :v1  do
      resources :tokens,:only => [:create, :destroy]
      resources :topics, :controller=>:topics_api do
        get :trending, on: :collection
      end

      resources :comments
      get 'search', :to => "topics_api#search"
      match "/user/info" => "users_api#info"
      match "/topics/create" => "topics#create"
    end
  end

  # Authentication
  devise_for :users,
    :path_names => {
      :sign_in => '/login',
      :sign_out => '/logout',
      :sign_up => '/join',
    },
    :controllers => {
      :sessions     => "sessions",
      :registrations => "registrations",
      :omniauth_callbacks => "omniauth_callbacks"
    }

  devise_scope :user do
    get "login",   :to => "sessions#new"
    post "login",  :to => "sessions#create"
    get "logout",  :to => "sessions#destroy"
    get "join",  :to => "registrations#new"
    post "join", :to => "registrations#create"
    get 'brands/join', :to => 'registrations#new', :brand => true
  end

  # Payments
  match '/topics/:topic_shortcode/payments/process' => 'payments#processP'
  match '/orders/:order_id/:invoice_id/confirmation' => 'payments#confirmation'
  # Passbook
  match '/passbook/passes/generate' => "passbook#generate"
  match '/passbook/passes/:aftoken' => "passbook#pass"
  match "/passbook/passes/v1/devices/:devid/registrations/:bundleid/:serialnumber" => "passbook#register_device", :constraints => { :bundleid => /[^\/]+/ }
  match "/passbook/passes/v1/passes/:typeid/:serialnumber" => "passbook#get_current_pass", :constraints => { :typeid => /[^\/]+/ }

  # match "/tokens/facebook" => "social#authenticateMobile"
  match "/tokens/facebook" => "social#socialAuthenticationAPIFacebook"
  match "/tokens/twitter" => "social#socialAuthenticationAPITwitter"
  match "/topics/findByMIU" => "social#getShortCode"
  match "/social/mobile/askfriends" => "social#askMobileFriends"

  # Scraping
  post 'get/product' => 'get#product'
  post 'get/images_and_price' => 'get#images'

  # Auth Roots
  get 'welcome' => 'profile#welcome', :as => 'welcome'
  get 'me' => 'profile#show', :as => 'user_root'
  #get 'me' => 'topics#index', :as => 'user_root'
  resource :profile, :controller => "profile"
  resources :haves do
    member do
      get 'copy'
      put 'recommend'
    end
  end

  # Topics
  resources :topics do
    resources :votes, only: :create
    resources :comments, only: :create
    resources :email_shares, only: [:new, :create]

    resources :responses
    get 'login' => 'topics#login'
    get 'thanks' => 'promotions#opinion'

    collection do
      get 'recommendation' => 'topics#new', :topic => { :form => :recommendation }
      get 'business/recommendation' => 'topics#new', :topic => { :form => :business_recommendation }
      get 'recommend' => 'topics#new', :topic => { :form => :recommend }
    end

    member do
      get 'copy'
      get 'bought'
    end
  end

  get 'activity' => 'activity#index'

  # Users
  resources :users, :only => [:index, :show]
  resources :brands, :only => [:index, :show]

  # Products
  resources :products do
    get 'feedback' => 'reviews#feedback'
    get 'feedback/thanks' => 'reviews#thanks'
    resources :reviews
  end

  # Social
  post 'social/tweeted' => 'social#tweeted'
  post 'social/recommended' => 'social#recommended'
  # Sharing
  match 'topics/:sc/social/ask/facebook' => 'social#facebook', as: :social_ask_facebook
  match 'topics/:sc/social/ask/twitter' => 'social#twitter',   as: :social_ask_twitter
  match 'topics/:sc/social/ask/all' => 'social#askAll'
  # Authentication
  match 'users/auth/methods/facebook/uid' => 'social#socialAuthenticationAPI'

  # Linking
  match 'profile/unlink/facebook' => 'social#unlinkFacebookAccount'
  match 'profile/unlink/twitter' => 'social#unlinkTwitterAccount'

  # Router
  get 'share/:shortcode' => "router#shared", :as => :shared
  get 'invited/:shortcode' => "router#invited", :as => :invited
  post 'register' => 'router#register', :as => :register
  post 'join_beta' => 'router#join_beta', :as => :join_beta

  # Uploads
  post 'uploads/accept' => 'upload#accept'


  # Sandbox
  get 'sandbox' => "website#sandbox"

  # Fragments
  get 'partial/:action' => 'fragments'

  # Brands / Shoppers
  get '/shoppers' => 'website#index', :shopper => true

  # Search
  get "/search", :to => "search#public"

  resources :welcomes, only: :index
  resources :tags, :only => :index do
    member do
      get :topics
    end
    collection do
      post :update_tags
    end
  end

  resource :invite do
    put :update_password, on: :member
  end

  # in config/routes.rb
  match "/pages/*id" => 'pages#show', :as => :page, :format => false

  # Root
  root :to => "welcomes#index"
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # Pageless
  index_with_xhr

  # Authenticate
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :find_topic_by_id!, :redirect_to_have!, only: :show
  before_filter :find_current_user_topic!, only: [:bought, :update, :edit, :destroy]

  respond_to :html, :js

  # Custom Actions
  layout :choose_layout

  # Verify Owner
  before_filter :only => [:edit, :update, :destroy] do
    unless @topic.user == current_user
      redirect_to login_path
    end
  end

  def feedback
    new!
  end

  def new
    @topic = Topic.new(params[:topic])
    @selected_tab = @topic.ihave? ? 'ihave' : 'mightbuy'
  end

  def index
    page = params[:page] || 1
    @topics = Topic.except_user_topics(page)
    if request.xhr?
      render :partial => "/topics/topic_list"
    end
  end

  def show
    @vote = @topic.votes.find_by_user_id(current_user.id) if current_user
    @comments = @topic.ordered_comments
    @comment = Comment.new

    if current_user && @topic.owner?(current_user)
      @selected_tab = 'mightbuy'
    else
      @selected_tab = "everybody"
      render template: "/topics/other_user_topic"
    end
  end

  def bought
    @topic.status = "ihave"
    @selected_tab = "ihave"
    @have = @topic
    render file: "haves/copy"
  end

  def copy
    @old_topic = Topic.find_by_shortcode(params[:id])
    @topic = @old_topic.copy(current_user)
    if @topic.save
      flash[:notice] = "Item copied to your list"
      redirect_to topic_path(@topic)
    else
      flash[:error] = "Failed to copy item"
      redirect_to topic_path(@old_topic)
    end
  end

  def create
    @topic = Topic.build_from_form_data(params['topic'],current_user,visitor_code)
    @topic.save

    redirect_path = @topic.ihave? ? have_path(@topic) : topic_path(@topic)
    respond_with(@topic, location: redirect_path)
  end

  def edit
    @selected_tab = 'mightbuy'
  end

  def update
    @topic.update_from_form_data(params['topic'],visitor_code)

    redirect_path = @topic.ihave? ? have_path(@topic) : topic_path(@topic)
    respond_with(@topic, location: redirect_path)
  end

  def destroy
    @topic.destroy
    flash[:notice] = "The item has been removed"
    redirect_to profile_path()
  end

  protected
  def search
    if params[:user]
      owner = current_user.id == params[:user].to_i
      search = end_of_association_chain.where(:user_id => params[:user])
      owner ? search : search.publics
    else
      end_of_association_chain.publics
    end
  end

  private

  helper_method :featured_response, :responses
  def featured_response
    unless params[:feature].blank?
      @response ||= @topic.responses.find_by_id(params[:feature])
    end
  end

  def choose_layout
    current_user ? 'logged_user' : 'anonymous'
  end

  def responses
    @responses ||= @topic.responses.joins(:user).includes(:replies).where(:reply_id => nil)
  end

  def redirect_to_have!
    if @topic.ihave?
      redirect_to have_path(@topic)
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def filter_url (type)
    topic_responses_path(resource, :filter_by => type, :format => :js)
  end

  def title
    case action_name
      when :show then super truncate(resource.subject, :length => 50)
      when :index then super "Latest Topics"
      when :new, :create then super "Start a Topic"
      when :edit, :update then super "Update your Topic"
    end
  end
  
  def respond_button (type, label, options = {})
    icon = options[:icon] ? image_tag('/images/icons/%s' % options[:icon]) : nil
    label = [ icon, label ].compact.join(' ').html_safe
    link_to label, 'javascript:void(0);', :class => ['button', type].join(' ')
  end

  def shared_this (share, format = nil)
    case share
      when Shares::Email
        type   = :email
        with   = mail_to(share.with)
        format ||= "%s shared this with %s %s."
      when Shares::Tweet
        with   = nil
        type   = :tweet
        format ||= "%1$s tweeted about this %3$s."
      when Shares::Recommend
        with = nil
        type = :recommend
        format ||= "%1$s recommend this on facebook %3$s."
    end
    
    info = user_info(share.user)
    user_link = link_to(info[:name], info[:path], :class => "user")
    created_at = content_tag( :span, shorthand(share.created_at).downcase, :class => "created-at" )
    
    content_tag :div, :class => "share #{type}" do
      (format % [ user_link, with, created_at ]).html_safe
    end
  end
  
  def said_this (response, format = nil)
    if response.is_a?(Response)
      name = response.user ? response.user.name : (response.share ? (user_signed_in?? response.share.with : "Guest") : "Guest" )
      path = response.user ? user_path(response.user) : "#guest"
      ((format || "%s said this %s.") % [
        link_to(name, path, :class => "user"),
        content_tag( :span, shorthand(response.created_at).downcase, :class => "created-at" )  
      ]).html_safe
    else 
      super(response, format)
    end
  end
  
  
  def shares_for_topic(social=nil)
    case 
      when owner_of_topic?
        social.nil?? resource.shares : (social ? resource.shares.social : resource.shares.email)
      else resource.shares.where(:user_id => current_user)
    end
  end
  
  def owner_of_topic?
    current_user == resource.user
  end

  def form_partial_for (topic)
    "topics/forms/%s" %
      case topic.form?
        when :business_recommendation then "business_recommendation"
        when :recommendation then "recommendation"
        when :recommend then "recommend"
        else "default"
      end    
  end

  def response_form_for (topic, &block)
    html = user_signed_in? ? {} : { "data-remote" => true }
    url    = topic_responses_path(topic, :format => user_signed_in? ? nil : :js)
    simple_form_for Response.new, :url => url, :html => html, &block
  end
  
  def open_graph_info
    if params[:feature]
      title = resource.share_title
      title = resource.subject if title.blank?
      {
        :title => title,
        :url   => request.url,
        :image => image_url(resource) { thumb('125x125#') },
        :desc  => featured_response.body
      }
    else
      case action_name
        when :show
          super.merge \
            :image => image_url(resource) { thumb('125x125#') },
            :desc  => truncate(resource.body, :length => 100)
        else super
      end
    end
  end

  def context_topic_path(topic)
    topic.ihave? ? have_path(topic) : topic_path(topic)
  end
  
  def invited_email_address
    share ? share.with : nil
  end
end

app/views/topics/_comment_entry.html.haml
.row
  .topic-comment-entry.mleft40.mright40
    .span1= image_tag avatar_image(comment.user)
    .span8
      %p.username= comment.user.name      
      %p= simple_format(comment.description)

    .clear
    %hr.mleft20.mtop15.mbot15.comment-hr

app/views/topics/_deals.html.haml
#topic-deals
  .span4
    - if @topic.product.bargin and (@topic.product.bargin.public or @topic.user == current_user)
      %h3 Deals
      .bargin
        .description
          = @topic.product.bargin.description

          - if @topic.product.bargin.accept_payments == true && @topic.product.bargin.payment_type == "MightBuy"
            %form{ action: "/topics/#{@topic.shortcode}/payments/process", method: :post, style: "margin-left: 40px;"}
              %script.stripe-button{ data: { address: '', amount: ((@topic.product.price*100.0)*@topic.product.bargin.value.to_f/100).to_i, key: 'pk_LdHsiwROde1xSfRJxlblt2gNiCD8m' }, src: 'https://button.stripe.com/v1/button.js' }

          - else
            - if @topic.bargin_valid?
              - if @topic.product.bargin.other and not @topic.product.bargin.other.blank?
                %br
                = @topic.product.bargin.other
                %br
              - if @topic.product.bargin.url and not @topic.product.bargin.url.blank?
                %br
                = link_to 'Get Deal!', @topic.product.bargin.url, class: 'btn-large btn-danger'

            - elsif @topic.product.bargin.bargin_conditions.length > 0
              .deals
                - if @topic.product.bargin.bargin_conditions.length > 0
                  %span.vote-count
                    = @topic.product.bargin.humanize
                    \=
                %span.percent-off
                  = @topic.product.bargin.offer
              %br

app/views/topics/_share_fields.html.slim
.nested-fields
  = f.input :with, :label => "Email", :placeholder => "yourfriends@email.com"
  = f.input :type, :as => :hidden, :input_html => { :value => Shares::Email }
  = link_to_remove_association "remove", f

app/views/topics/_social_share_topic.html.haml
.share-topic-link
  Ask Friends - should you buy it?

  %ul.horizontal-list.mtop20
    %li
      = link_to new_topic_email_share_path(topic), remote: true do
        .email-icon

    %li
      = link_to "javascript:void(0);", "data-tweet-intent" => twitter_url(topic), class: "tweet-topic" do
        .twitter-icon

    %li
      = link_to "javascript:void(0);", facebook_data_params(topic).merge(class: "like-topic") do
        .facebook-icon
  .clear

app/views/topics/_topic_meta_information.html.haml
.row
  %hr.mleft60.mright40
  .topic-votes-and-deals
    #topic-percentage-row
      = render :partial => "/topics/vote_statistics", locals: {topic: @topic}
    - if @topic.has_bargin?
      = render :partial => "/topics/deals", locals: {topic: @topic}
    .clear

.row
  .span6
    %h3.mleft40.mtop20.mbot30 Write Responses

.topic-comments
  - @comments.each do |comment|
    = render partial: "topics/comment_entry", locals: { comment: comment }

.row
  .new-topic-comment.mleft40
    .span1= image_tag(avatar_image)
    .span8.mbot30
      = simple_form_for [@topic, @comment], remote: true do |f|
        = f.input :description, label: false, input_html: { rows: 3 }
        = f.submit "Comment", :class=>"btn btn-green pull-right"

app/views/topics/_topic_recommend.html.haml
.topic-recommend
  Recommend this item?
  %ul.horizontal-list.mtop20
    %li
      = link_to recommend_topic_path(topic, recommend: "yes"), method: :put, remote: true do
        .topic-recommend-yes-icon{id: topic.recommendable? ? "topic-recommend-yes" : ""}
    %li
      = link_to recommend_topic_path(topic, recommend: "no"), method: :put, remote: true do
        .topic-recommend-no-icon{id: topic.recommendable? ? "topic-recommend-no" : ""}

app/views/topics/_topic_votes_on_list.html.haml
.span3
  .color-brown= "Vote - should #{topic.poster_name(current_user)} buy it?"
  .vote-icons.pull-left
    = link_to topic_votes_path(topic, vote: "yes"), method: :post, remote: true do
      .vote-yes{class: vote && vote.buyit ? "checked" : ""}
    = link_to topic_votes_path(topic, vote: "no"), method: :post, remote: true do
      .vote-no{class: vote && !vote.buyit ? "checked" : ""}
  .clear

app/views/topics/_vote_statistics.html.haml
.span5
  %h3= "Votes #{topic.vote_statistics[:number][:total]}"
  %div.vote-statistics
    %span.yes-votes
      .yes-no-flag
        Yes
      .percentage
        = topic.vote_statistics[:percentage][:yes]
        \%
      .number
        = "#{topic.vote_statistics[:number][:yes]} / #{topic.vote_statistics[:number][:total]}"
    %span.no-votes
      .yes-no-flag
        No
      .percentage
        = topic.vote_statistics[:percentage][:no]
        \%
      .number
        = "#{topic.vote_statistics[:number][:no]} / #{topic.vote_statistics[:number][:total]}"
  .clear

app/views/topics/copy.html.haml
= javascript_tag "Mightbuy.initialTags = #{@old_topic.tag_array}"
%div#details
  .row
    .span5
      .topic-form-wrapper
        = simple_form_for @topic do |form|
          = render "/topics/forms/default", :form => form
          .buttons.btn-red-large.w115
            = form.button :submit, "Save"
    %div#topic_right_panel.span5
      %div#gsearch-results{style: "display:none;"}
      %div#item-form-image-selector
    .clear

app/views/topics/feedback.html.slim
= app_page do

  = simple_form_for resource, :url => topics_path do |form|
  
    = heading "Choose an Image for your Product.."
    
    .image-selector-uploader.input.string
      .image-holder
        a href="javascript:void(0);" class="image blank"
          = centered {}
        .controls
          a href="#prev" class="prev" Previous
          a href="#next" class="next" Next
      .web
        label Grab one from the web..
        .field
          input type="text" placeholder="http://www.myshop.com/myproduct"
          = link_to "Grab", "#get", :class => "button get"
          .clearfix
      .computer
        label Or one from your computer..
        .field
          = link_to "Select a File..", "#select", :class => "button select"
      = form.input :remote_image_url, :as => :hidden, :input_html => { :class => "remote-url" }
  
    = heading "What Would you Like To Ask?"
  
    = form.input :subject, :label => "Your Question", :placeholder => "What do you think of your new shoes?"
    = form.input :body, :label => "Description", :placeholder => "Did they fit well? Were they stylish or sleek? Etc.", :hint => "Elaborate further on what type of feedback you'd like."
          
    
    / = form.input :image, :as => :file, :label => "Your Image..", :hint => "Choose an image from your hard drive.", :input_html => { :class => "special" }
    
    / Customers
    = heading "Which Customers Should We Ask?"
    
    = form.simple_fields_for :shares, form.object.shares.new do |fields|
      = render "share_fields", :f => fields
    .links
      = link_to_add_association 'Send to another customer..', form, :shares
    
    / Other
    = heading "Other Fields.."
    
    = form.input :recommendable, :label => "Recommendations", :hint => "Would you like users to be able to recommend this?", :as => :radio
    = form.input :access, :label => "Who can view?", :collection => Topic::Access, :as => :radio    
    
    .buttons
      = form.button :submit, "Send!"
      = go_back(collection_path)

app/views/topics/index.html.haml
%div#details
  %ol.list.topics#pageless-topic-listing{:"data-total-pages"=>"#{@topics.num_pages}"}
    = render :partial => "topic_list"

app/views/topics/new.html.haml
%div#details
  .row
    .span5
      .topic-form-wrapper
        = simple_form_for @topic do |form|
          = render "/topics/forms/default", :form => form
          .buttons.btn-red-large.w115
            = form.button :submit, "Save"
    %div#topic_right_panel.span5
      %div#gsearch-results.hide
      %div#item-form-image-selector
    .clear
:javascript
  $(function() {
    $('textarea').autogrow();
  });

app/views/topics/other_user_topic.html.haml
= title_tag @topic.subject

.show-topic
  .row.topic-links.ptop40.mleft20.mright40
    .span9
      .recommended-flag
        = link_to user_path(@topic.user) do
          #{@topic.poster_name}
        %span.text
          \&nbsp;##{@topic.human_status}
          this

        - if @topic.recommended?
          %span.text &nbsp;and
          %span.recommended-tag
            %span.recomend-icon
            Recommended it!

      .share-links
        %span.text
          Share

        - twitter_share_url = twitter_url(@topic)
        - facebook_share_url = facebook_url(@topic)

        = link_to new_topic_email_share_path(@topic), class: "email-icon", data: { remote: true } do
          &nbsp;
        = link_to twitter_share_url, class: "twitter-icon", data: { 'tweet-intent' => twitter_share_url } do
          &nbsp;
        = link_to facebook_share_url, facebook_data_params(@topic).merge(class: "facebook-icon like-topic") do
          &nbsp;

    - if current_user
      .pull-right
        .btn-group
          = link_to "#", class: "btn btn-danger btn-small dropdown-toggle", "data-toggle" => "dropdown" do
            Add to list
            %span.caret
          %ul.dropdown-menu
            %li= link_to "I might buy", copy_topic_path(@topic.shortcode)
            %li.divider
            %li= link_to "I have", copy_have_path(id: @topic.shortcode)
        .clear
    %hr.mtop7-mbot0.span9
  .row.mtop50
    = render :partial => "topic_detail"

  .row
    .span5
      \&nbsp;
    .span5{class: current_user ? "" : "offset4"}
      #topic-voting.pleft40
        = render partial: "topics/topic_votes", locals: { topic: @topic, vote: @vote }

  = render :partial => "topic_meta_information"

app/views/topics/show.html.haml
= title_tag @topic.subject
= javascript_tag "Mightbuy.initialTags = #{@topic.tag_array}"

= link_to new_have_path, class: "btn btn-red add-item" do
  %i.icon-plus-sign.icon-white
  Add an item
.show-topic
  .row.topic-links.ptop40.mleft20.mright40
    .span3
      = link_to profile_path, :class => "btn btn-red btn-small" do
        %i.icon-chevron-left.mtop1.icon-white
        Back to list view

    - if current_user == @topic.user
      %ul.nav.nav-pills.pull-right
        %li.dropdown
          %a#drop4.dropdown-toggle.btn.btn-red.btn-small{"data-toggle" => "dropdown", :href => "#", :role => "button"}
            %i.icon-cog.icon-white.mtop1
            %b.caret
          %ul.dropdown-menu{"aria-labelledby" => "drop4", :role => "menu"}
            %li
              = link_to(bought_topic_path(@topic), :tabindex => "-1") do
                %i.icon-plus
                &nbsp;Add to have
            %li.divider
            %li
              = link_to edit_topic_path(@topic), :tabindex => "-1" do
                %i.icon-ok
                &nbsp;Update
            %li.divider
            %li
              = link_to topic_path(@topic), method: :delete, confirm: "Are you sure, you want to delete?", :tabindex => "-1" do
                %i.icon-remove
                &nbsp;Remove
    %hr.mtop7-mbot0.span9
  .row.mtop50.mbot30
    = render :partial => "/topics/topic_detail"

  .row
    .span10
      #social-sharing.mleft40
        = render partial: "/topics/social_share_topic", locals: { topic: @topic }

  = render :partial => "/topics/topic_meta_information"